# Documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '11:00'
      timezone: 'Europe/Zurich'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    reviewers:
      - '@UN-OCHA/hpc-js-reviewers'
    groups:
      jest:
        applies-to: version-updates
        patterns:
          - 'jest'
          - '@types/jest'
          - 'ts-jest'
    ignore:
      - dependency-name: 'node-fetch'
        update-types: [version-update:semver-major]
      - dependency-name: 'fp-ts'
      - dependency-name: 'io-ts'
