version: '3.8'
services:
  api:
    container_name: hpc_api
    build:
      context: .
      dockerfile: ./env/api/Dockerfile
    volumes:
      - .:/srv/www
    environment:
      - POSTGRES_CONNECTION_STRING=postgres://postgres:demo@db:5432/demo
      - NODE_ENV=development
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=120
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:11.7
    container_name: hpc_postgres_db
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    volumes:
      - ./env/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
